interface PricingDetails {
  title: string;
  packageName: string;
  pricing: string;
  quality: string;
  listDetails: string[];
}

const ComboPricingContent: PricingDetails[] = [
  {
    title: "logo-design",
    packageName: "Basic Combo Package",
    pricing: "619.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "5 Custom Logo Design Concepts",
      "By 2 Designers",
      "Icon Design",
      "All Final File Formats",
      "Business Card, Letterhead, Envelope, Fax Template",
      "MS Word Letterhead",
      "5 Page Website",
      "Mobile Responsive*",
      "Team of Expert Designers & Developers",
      "8 Stock images",
      "5 Banner Designs",
      "jQuery Sliders",
      "Free Google Friendly Sitemap",
      "Facebook Page Design",
      "Complete W3C Certified HTML",
      "Complete Deployment",
      "Logo Design Final Files (.PNG, .JPG, .PDF)",
      "Website Design Complete Source Files",
      "Dedicated Project Manager",
      "Complete Deployment",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Start Up Combo Package",
    pricing: "994.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "Icon Design",
      "All Final File Formats",
      "Business Card, Letterhead, Envelope, Fax Template",
      "MS Word Letterhead",
      "UNLIMITED Pages Website",
      "Content Management System (CMS)",
      "Mobile Responsive*",
      "5 Stock Photos + 3 Banner Designs",
      "Any 3 Social Media Platforms",
      "Complete W3C Certified HTML",
      "Complete Deployment",
      "Dedicated Account Manager",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Professional Combo Package",
    pricing: "1299.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Concepts",
      "8 Dedicated Designers",
      "Icon Design",
      "Unlimited Revisions",
      "All file formats",
      "– Print Materials",
      "2 Free Custom Stationary Designs",
      "MS Word Letterhead",
      "Free Trifold Brochure Design",
      "Unlimited Pages Design",
      "Conceptual and Dynamic Liquid Website",
      "Team of Expert Designers & Developers",
      "Word Press OR Custom Php",
      "Content Management System",
      "Mobile Responsive",
      "Online Reservation/Appointment Tool (Optional)",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Newsfeed Integration",
      "Social Media Integration",
      "Search Engine Submission",
      "15 Stock images",
      "8 Unique Banner Designs",
      "jQuery Sliders",
      "Free Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Google+ Page Design",
      "Dedicated Account Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Elite Combo Package",
    pricing: "1529.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "9 Logo Design Idea(s)",
      "By 4 Expert Level Designer(s)",
      "Free Icon Design",
      "Unlimited Revisions",
      "2 to 3 Business Days TAT",
      "Letterhead Design",
      "Business Card Design",
      "Envelope Design",
      "Email Signature Design",
      "Electronic Letterhead",
      "Invoice Design",
      "Unique 5 Pages Website Design",
      "Custom, Interactive, Dynamic & High End Web Design",
      "Custom WordPress Development",
      "5 Stock Images",
      "5 Banner Designs",
      "Sliding Banners",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System (WordPress)",
      "Mobile Responsive",
      "Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)",
      "FREE 12 Months Domain Name",
      "FREE 12 Month Hosting",
      "5 Professional Email ID’s",
      "Social Media Page Integration",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete W3C Certified HTML ",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Facebook Icon Image & Banner Design",
      "Twitter Icon Image & Banner Design",
      "Google+ Icon Image & Banner Design",
      "Logo Design Final Files (.AI, .PSD, .EPS, .PNG, .JPG, .PDF, .TIFF)",
      "Website Design Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights*",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "Professional Content/Copywriting",
      "Online Payment Integration",
      "Shopping Cart Integration",
      "Additional Professional Email ID",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Business Combo Package",
    pricing: "1799.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Design Idea(s)",
      "8 Dedicated Designers",
      "Icon Design",
      "All final file formats",
      "2 Free Custom Stationary Designs",
      "MS Word Letterhead",
      "Invoice Design",
      "FREE Tri fold Brochure Design",
      "Unlimited Pages Website",
      "Conceptual and Dynamic Website",
      "Word Press OR CUSTOM PHP ",
      "Content Management System (CMS)",
      "Easy Product Search",
      "Product Reviews",
      "Unlimited Products",
      "Unlimited Categories",
      "Promotional Product Showcase ",
      "New Product Showcase",
      "Full Shopping Cart Integration",
      "Payment Module Integration ",
      "Sales & Inventory Management",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Newsfeed Integration",
      "Social Media Integration ",
      "Search Engine Submission ",
      "Team of Dedicated Designers, Developers and Brand Experts",
      "20 Stock images",
      "6 Unique Banner Designs",
      "jQuery Slider",
      "Free Google Friendly Sitemap ",
      "Complete W3C Certified HTML ",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Google+ Page Design",
      "Pinterest Page Design",
      "Dedicated Account Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Gold Combo Package",
    pricing: "3999.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Design Idea(s)",
      "8 Dedicated Designers",
      "Icon Design",
      "All final file formats",
      "2 Free Custom Stationary Designs",
      "MS Word Letterhead",
      "Invoice Design",
      "FREE Tri fold Brochure Design",
      "Unlimited Pages Website",
      "Conceptual and Dynamic Website",
      "Word Press OR CUSTOM PHP ",
      "Content Management System (CMS)",
      "Easy Product Search",
      "Product Reviews",
      "Unlimited Products",
      "Unlimited Categories",
      "Promotional Product Showcase ",
      "New Product Showcase",
      "Full Shopping Cart Integration",
      "Payment Module Integration ",
      "Sales & Inventory Management",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Newsfeed Integration",
      "Social Media Integration ",
      "Search Engine Submission ",
      "Team of Dedicated Designers, Developers and Brand Experts",
      "20 Stock images",
      "6 Unique Banner Designs",
      "jQuery Slider",
      "Free Google Friendly Sitemap ",
      "Complete W3C Certified HTML ",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Google+ Page Design",
      "Pinterest Page Design",
      "Dedicated Account Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  
 
];

export default ComboPricingContent;
