interface PricingDetails {
  title: string;
  packageName: string;
  pricing: string;
  quality: string;
  listDetails: string[];
}

const PricingContent: PricingDetails[] = [
  {
    title: "logo-design",
    packageName: "instant basic Package",
    pricing: "49.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "3 Logo Design",
      "By 2 Different Logo Designers",
      "Final Files (JPEG & PNG)",
      "3 Revisions (Additional Revision Per Change $10) ",
      "100% Unique Custom Logo Design Concepts",
      "100% Approval Assurance ",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Logo StartUp Package",
    pricing: "99.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "6 Logo Design",
      "2 Dedicated Logo Designer ",
      "5 Revisions",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager"
    ],
  },
  {
    title: "logo-design",
    packageName: "Instant Gold Package",
    pricing: "155.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "10 Logo Design ",
      "By 8 Different Logo Designers ",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Free Electronic Letterhead ",
      "Free Invoice Design",
      "JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Logo Infinite Package",
    pricing: "299.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Original Logo Concepts",
      "8 Dedicated Logo Designer (Industry Specific) ",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "500 Business Cards",
      "Web Design Mock-up",
      "3 sec animation ",
      "Email Signature Design",
      "With Grey Scale Format",
      "Final Files (.AI, .PSD, .EPS, .JPEG, .webp, .PDF)",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "logo-design",
    packageName: "Logo Platinum Package",
    pricing: "599.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Original Logo Concepts",
      "8 Dedicated Logo Designer (Industry Specific) ",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "social media banners for Facebook, Instagram, Twitter, Linkedin and Pinterest",
      "T-shirt design",
      "Brand Book ",
      "500 Business Cards",
      "500 Letterheads",
      "Email Signature Design",
      "Social Media Designs (Facebook, Twitter, Instagram)",
      "2 Sided Flyer OR Bi-Fold Brochure Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "website-design",
    packageName: "Basic Website",
    pricing: "399.00",
    quality: "",
    listDetails: [
      "3 Page Website",
      "Custom Layout Design",
      "Contact/Query Form",
      "1 Banner Design",
      "2 Stock Photos ",
      "FREE Favicon Design",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee ",
      "Value Added Services ",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "website-design",
    packageName: "Start Up Website",
    pricing: "899.00",
    quality: "",
    listDetails: [
      "5 Page Website ",
      "Custom Layout Design ",
      "Contact/Query Form ",
      "3 Banner Designs ",
      "5 Stock Photos",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap",
      "Unlimited Revisions",
      "Complete W3C Certified HTML ",
      "Website Initial Concepts in 48 Hours ",
      "Complete Design & Deployment ",
      "Complete Source Files",
      "Dedicated Project Manager ",
      "100% Ownership Rights ",
      "100% Satisfaction Guarantee ",
      "100% Money Back Guarantee ",
      "Value Added Services ",
      "Mobile Responsive will be Additional $200* ",
      "CMS will be Additional $250* ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "website-design",
    packageName: "Professional Website",
    pricing: "1499.00",
    quality: "",
    listDetails: [
      "Up to 10 Unique Pages Website ",
      "CMS /Admin Panel Integration ",
      "5+ Stock Photos & Banner Designs ",
      "FREE Social Media Integration ",
      "FREE Favicon Design ",
      "FREE Google Friendly Sitemap ",
      "Unlimited Revisions",
      "Cross Browser Compatible ",
      "Complete W3C Certified HTML ",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Custom, Interactive & Dynamic Web Design ",
      "Industry specified Team of Expert Designers and Developers ",
      "Complete Source Files ",
      "Dedicated Project Manager ",
      "100% Ownership Rights ",
      "100% Satisfaction Guarantee ",
      "100% Money Back Guarantee ",
      "Value Added Services ",
      "Mobile Responsive will be Additional $200* ",
      "CMS will be Additional $250* ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "website-design",
    packageName: "Corporate Website",
    pricing: "3999.00",
    quality: "",
    listDetails: [
      "Up to 10 Unique Pages Website ",
      "Custom Made, Interactive & Dynamic Design ",
      "Customized WordPress or PHP Development ",
      "Fully Mobile Responsive ",
      "Interactive Sliding Banners ",
      "Up to 10 Custom Made Banner Designs ",
      "10 Stock Images ",
      "Unlimited Revisions ",
      "Content Management System ",
      "Online Signup Area (For Newsletters, Offers etc.) ",
      "Search Bar ",
      "Live Feeds of Social Networks integration (Optional) ",
      "Up to 15 Professional Email ID’s ",
      "Google Friendly Sitemap ",
      "Search Engine Submission ",
      "Cross Browser Compatible ",
      "Complete W3C Certified HTML ",
      "Industry specified Team of Expert Designers and Developers ",
      "Complete Deployment ",
      "Complete Source Files ",
      "Dedicated Project Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE* ",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "website-design",
    packageName: "Platinum Website",
    pricing: "6999.00",
    quality: "",
    listDetails: [
      "Up to 20 Unique Pages Website ",
      "Custom Made, Interactive, Dynamic & High-End Design ",
      "Customized WordPress or PHP Development ",
      "Fully Mobile Responsive ",
      "Interactive Sliding Banners ",
      "Up to 15 Custom Made Banner Designs",
      "15 Stock Images ",
      "Unlimited Revisions",
      "Content Management System",
      "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional) ",
      "Multi Lingual (Optional) ",
      "Custom Dynamic Forms (Optional) ",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional) ",
      "Up to 15 Professional Email ID’s ",
      "Google Friendly Sitemap ",
      "Search Engine Submission ",
      "Cross Browser Compatible ",
      "Complete W3C Certified HTML ",
      "Industry specified Team of Expert Designers and Developers ",
      "Complete Deployment ",
      "Complete Source Files ",
      "Dedicated Project Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "combo",
    packageName: "Basic Combo Package",
    pricing: "619.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "5 Custom Logo Design Concepts",
      "By 2 Designers",
      "Icon Design",
      "All Final File Formats",
      "Business Card, Letterhead, Envelope, Fax Template",
      "MS Word Letterhead",
      "5 Page Website",
      "Mobile Responsive",
      "Team of Expert Designers & Developers",
      "8 Stock images",
      "5 Banner Designs",
      "jQuery Sliders",
      "Free Google Friendly Sitemap",
      "Facebook Page Design",
      "Complete W3C Certified HTML ",
      "Complete Deployment",
      "Logo Design Final Files (.PNG, .JPG, .PDF)",
      "Website Design Complete Source Files",
      "Dedicated Project Manager ",
      "Complete Deployment",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "combo",
    packageName: "Start Up Combo Package",
    pricing: "994.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "Icon Design",
      "All Final File Formats",
      "Business Card, Letterhead, Envelope",
      "MS Word Letterhead",
      "UNLIMITED Pages Website ",
      "Content Management System (CMS)",
      "Mobile Responsive",
      "5 Stock Photos + 3 Banner Designs",
      "Any 3 Social Media Platforms",
      "Complete W3C Certified HTML ",
      "Complete Deployment",
      "Dedicated Account Manager ",
      "Complete Deployment",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "combo",
    packageName: "Professional Combo Package",
    pricing: "1299.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Concepts",
      "8 Dedicated Designers",
      "Icon Design",
      "Unlimited Revisions",
      "All file formats",
      "– Print Materials",
      "2 Free Custom Stationary Designs",
      "MS Word Letterhead",
      "Free Trifold Brochure Design ",
      "Unlimited Pages Design",
      "Conceptual and Dynamic Liquid Website",
      "Team of Expert Designers & Developers",
      "Word Press OR Custom Php ",
      "Content Management System ",
      "Mobile Responsive",
      "Online Reservation/Appointment Tool (Optional)",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Newsfeed Integration",
      "Social Media Integration ",
      "Search Engine Submission ",
      "15 Stock images",
      "8 Unique Banner Designs",
      "jQuery Sliders",
      "Free Google Friendly Sitemap",
      "Complete W3C Certified HTML ",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Google+ Page Design",
      "Dedicated Account Manager ",
      "100% Ownership Rights",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "combo",
    packageName: "Elite Combo Package",
    pricing: "1529.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "9 Logo Design Idea(s)",
      "By 4 Expert Level Designer(s)",
      "Free Icon Design",
      "Unlimited Revisions",
      "2 to 3 Business Days TAT ",
      "Letterhead Design",
      "Business Card Design",
      "Envelope Design",
      "Email Signature Design",
      "Electronic Letterhead",
      "Invoice Design",
      "Unique 5 Pages Website Design",
      "Custom, Interactive, Dynamic & High End Web Design",
      "Custom WordPress Development",
      "5 Stock Images",
      "5 Banner Designs",
      "Sliding Banners",
      "Unlimited Revisions",
      "Special Hoover Effects",
      "Content Management System (WordPress)",
      "Mobile Responsive",
      "Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)",
      "FREE 12 Months Domain Name ",
      "FREE 12 Month Hosting",
      "5 Professional Email ID’s ",
      "Social Media Page Integration",
      "Google Friendly Sitemap ",
      "Search Engine Submission ",
      "Complete W3C Certified HTML ",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Facebook Icon Image & Banner Design",
      "Twitter Icon Image & Banner Design",
      "Google+ Icon Image & Banner Design",
      "Logo Design Final Files (.AI, .PSD, .EPS, .PNG, .JPG, .PDF, .TIFF)",
      "Website Design Complete Source Files",
      "Dedicated Project Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "Professional Content/Copywriting",
      "Online Payment Integration ",
      "Shopping Cart Integration ",
      "Additional Professional Email ID",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "combo",
    packageName: "Business Combo Package",
    pricing: "1799.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Design Idea(s)",
      "8 Dedicated Designers",
      "Icon Design",
      "All final file formats",
      "2 Free Custom Stationary Designs",
      "MS Word Letterhead",
      "Invoice Design",
      "FREE Tri fold Brochure Design",
      "Unlimited Pages Website ",
      "Conceptual and Dynamic Website",
      "Word Press OR CUSTOM PHP ",
      "Content Management System (CMS)",
      "Easy Product Search",
      "Product Reviews",
      "Unlimited Products",
      "Unlimited Categories",
      "Promotional Product Showcase",
      "New Product Showcase",
      "Full Shopping Cart Integration",
      "Payment Module Integration ",
      "Sales & Inventory Management",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Newsfeed Integration",
      "Social Media Integration ",
      "Search Engine Submission ",
      "Team of Dedicated Designers, Developers and Brand Experts",
      "20 Stock images",
      "6 Unique Banner Designs ",
      "jQuery Slider",
      "Free Google Friendly Sitemap",
      "Complete W3C Certified HTML ",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Google+ Page Design",
      "Pinterest Page Design",
      "Dedicated Account Manager ",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee ",
      "100% Money Back Guarantee ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "combo",
    packageName: "Gold Combo Package",
    pricing: "3999.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Unlimited Logo Design Idea(s)",
      "8 Dedicated Designers",
      "Icon Design",
      "All final file formats",
      "2 Free Custom Stationary Designs",
      "MS Word Letterhead",
      "Invoice Design",
      "FREE Tri fold Brochure Design",
      "Unlimited Pages Website ",
      "Conceptual and Dynamic Website",
      "Word Press OR CUSTOM PHP ",
      "Content Management System (CMS)",
      "Easy Product Search",
      "Product Reviews",
      "Unlimited Products",
      "Unlimited Categories",
      "Promotional Product Showcase",
      "New Product Showcase",
      "Full Shopping Cart Integration",
      "Payment Module Integration ",
      "Sales & Inventory Management",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Newsfeed Integration",
      "Social Media Integration ",
      "Search Engine Submission ",
      "Team of Dedicated Designers, Developers and Brand Experts",
      "20 Stock images",
      "6 Unique Banner Designs ",
      "jQuery Slider",
      "Free Google Friendly Sitemap",
      "Complete W3C Certified HTML ",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Google+ Page Design",
      "Pinterest Page Design",
      "Dedicated Account Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "ecommerce-solutions",
    packageName: "E-Commerce Basic Package",
    pricing: "449.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "E-Commerce Website Design and Development",
      "Theme Based Design",
      "2 Banner Designs",
      "Sliding Banner",
      "3 Stock Photos",
      "06 Revisions",
      "Hover Effects",
      "Up to 10 Products",
      "Up to 3 Categories",
      "Content/Inventory Management System",
      "Easy Product Search Bar ",
      "Shopping Cart Integration ",
      "Payment Module Integration ",
      "Direct Checkout",
      "Sign up Checkout",
      "Wishlist",
      "Complete W3C Validation ",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "ecommerce-solutions",
    packageName: "E-Commerce Start Up Package",
    pricing: "699.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "E-Commerce Website Design and Development",
      "High-end Theme Based Design ",
      "5 Banner Designs",
      "Sliding Banner",
      "5 Stock Photos",
      "12 Revisions",
      "Hover Effects",
      "Up to 25 Products",
      "Up to 5 Categories",
      "Content/Inventory Management System",
      "Easy Product Search Bar ",
      "Shopping Cart Integration ",
      "Payment Module Integration ",
      "Direct Checkout",
      "Sign up Checkout",
      "Wishlist",
      "Social Media Pages Integration",
      "Sitemap",
      "Complete W3C Validation ",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager ",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "ecommerce-solutions",
    packageName: "E-Commerce Elite Package",
    pricing: "1699.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, Unique Design",
      "10 Banner Designs",
      "Sliding Banner",
      "10 Stock Photos",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Up to 500 Products",
      "Up to 25 Categories",
      "Product Reviews & Ratings",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Easy Product Search Bar",
      "Shopping Cart Integration ",
      "Payment Module Integration ",
      "Direct Checkout",
      "Sign up Checkout",
      "Wishlist",
      "Social Media Pages Integration",
      "Blog page (If Required)",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "ecommerce-solutions",
    packageName: "E-Commerce Professional Package",
    pricing: "1199.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "E-Commerce Website Design and Development",
      "Customized Theme Based Design",
      "7 Banner Designs",
      "Sliding Banner",
      "7 Stock Photos",
      "Unlimited Revisions",
      "Hover Effects",
      "Up to 100 Products",
      "Up to 10 Categories",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Easy Product Search Bar ",
      "Shopping Cart Integration ",
      "Payment Module Integration ",
      "Direct Checkout",
      "Sign up Checkout",
      "Wishlist",
      "Social Media Pages Integration",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager ",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "ecommerce-solutions",
    packageName: "E-Commerce Identity Package",
    pricing: "2499.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, Interactive, Dynamic, Unique Design",
      "User-friendly Navigation ",
      "20 Banner Designs",
      "Sliding Banner",
      "20 Stock Photos",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Reviews & Ratings",
      "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
      "Product Rating",
      "Product Detail with Similar Product Range",
      "Product Comparison",
      "Discounted Products Showcase ",
      "New Arrival Products Showcase",
      "Discount Coupons",
      "Easy Product Search Bar",
      "Shopping Cart Integration ",
      "Payment Module Integration ",
      "Direct Checkout",
      "Sign up Checkout",
      "Wishlist",
      "Bulk Product Upload From Excel Sheet",
      "Export order into excel sheet",
      "Social Media Pages Integration",
      "Facebook Shop Setup",
      "Blog page (If Required)",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager ",
      " *NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "ecommerce-solutions",
    packageName: "E-Commerce Corporate Package",
    pricing: "3699.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, Interactive, Dynamic, Unique Design",
      "User-friendly Navigation ",
      "20 Banner Designs",
      "Sliding Banner",
      "20 Stock Photos",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Reviews & Ratings",
      "Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
      "Product Rating",
      "Product Detail with Similar Product Range",
      "Product Comparison",
      "Discounted Products Showcase ",
      "New Arrival Products Showcase",
      "Discount Coupons",
      "Easy Product Search Bar",
      "Shopping Cart Integration ",
      "Payment Module Integration ",
      "Direct Checkout",
      "Sign up Checkout",
      "Wishlist",
      "Bulk Product Upload From Excel Sheet",
      "Export order into excel sheet",
      "Social Media Pages Integration",
      "Facebook Shop Setup",
      "Blog page (If Required)",
      "Sitemap",
      "Complete W3C Validation",
      "Dedicated Team of Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager ",
      " *NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "animation",
    packageName: "Basic Video Package",
    pricing: "499.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "30 Second Video",
      "Professional Script",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "4 weeks Delivery",
      "Unlimited Revisions",
      "Dedicated Project Manager",
      "NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "animation",
    packageName: "Classic Video Package",
    pricing: "999.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "60 Second Video",
      "Professional Script",
      "Sample Theme",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "5 weeks Delivery",
      "Dedicated Project Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "animation",
    packageName: "Premium Video Package",
    pricing: "1499.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "90 Second Video",
      "Professional Script",
      "Sample Theme",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "6 Weeks Delivery",
      "Dedicated Project Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "animation",
    packageName: "Unlimited Video Package",
    pricing: "2299.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "120 Second Video",
      "Professional Script",
      "Sample Theme",
      "Storyboard",
      "Animation",
      "Voice - Over & Sound Effects",
      "Dedicated Project Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "nft-design",
    packageName: "NFT LABS LITE",
    pricing: "299.00",
    quality: "Premium Base Character Creation",
    listDetails: [
      "Base Character Creation",
      "3 Traits/Accessories",
      "2 revisions included",
      "Sourcefile",
      "Fully refundable until revision call",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "nft-design",
    packageName: "NFT ENTREPRENEUR",
    pricing: "2400.00",
    quality: "NFT Universe including 1,000 character variations.",
    listDetails: [
      "Base Character",
      "30 Traits/Accessories",
      "1,000 Variations",
      "Collection Generation",
      "Metadata",
      "Source Files",
      "2 Revisions included",
      "Fully refundable until revision call",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "nft-design",
    packageName: "NFT MOONSHOT",
    pricing: "4999.00",
    quality: "NFT Universe including 10,000 character variations and 3 revisions.",
    listDetails: [
      "Base Character",
      "70 Traits/Accessories",
      "10,000 Variations",
      "Collection Generation",
      "Metadata",
      "Source Files",
      "3 Revisions included",
      "Fully refundable until revision call",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "illustration",
    packageName: "Basic Illustrative Package",
    pricing: "294.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "3 Custom Logo Design Concepts",
      "By 2 Designers",
      "UNLIMITED Revisions",
      "48 to 72 hours TAT",
      "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
      "Dedicated Project Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "illustration",
    packageName: "Startup Illustrative Package",
    pricing: "394.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "4 Custom Logo Design Concepts",
      "By 3 Designers",
      "48 to 72 hours TAT",
      "UNLIMITED Revisions",
      "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
      "Dedicated Project Manager",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "illustration",
    packageName: "Professional Illustrative Package",
    pricing: "594.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "UNLIMITED Logo Design Concepts",
      "By 4 Designers",
      "UNLIMITED Revisions",
      "24 to 48 hours TAT",
      "Dedicated Project Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "illustration",
    packageName: "3D Logo Illustrative Package",
    pricing: "544.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "3 Unique 3D Logo Concepts",
      "Light Effects and VFX",
      "Fully Rendered",
      "Multiple 3D Angles",
      "By 3 Award Winning Designers",
      "72 hours Turnaround Time",
      "UNLIMITED Revisions",
      "Dedicated Project Manager",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "Startup Collateral Package",
    pricing: "99.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "2 Stationery Design Set",
      "FREE Fax Template",
      "Print Ready Formats",
      "UNLIMITED Revisions",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "Collateral Classic Package",
    pricing: "199.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "2 Stationery Design Set",
      "UNLIMITED Revisions",
      "Flyer Design",
      "Brochure Design (Bi-fold/Tri-fold)",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "Premium Collateral Package",
    pricing: "399.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "2 Stationery Design Set",
      "Packaging Design",
      "UNLIMITED Revisions",
      "T-Shirt Design",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "Unlimited Collateral Package",
    pricing: "499.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "2 Stationery Design Set",
      "Menu Card Design",
      "T-Shirt Design",
      "1 Banner Design",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "seo-services",
    packageName: "Basic Plan Package",
    pricing: "3500.00",
    quality: "(3 MONTHS PLAN)",
    listDetails: [
      "Prior Analysis",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "15 Selected Keywords Targeting",
      "15 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of anchors",
      "Tracking & Analysis",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ’s",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "seo-services",
    packageName: "Premium Plan Package",
    pricing: "6000.00",
    quality: "(6 MONTHS PLAN)",
    listDetails: [
      "Prior Analysis",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "30 Selected Keywords Targeting",
      "30 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of anchors",
      "Inclusion of anchors Indexing Modifications",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ’s",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "seo-services",
    packageName: "Platinum Plan Package",
    pricing: "8000.00",
    quality: "(12 MONTHS PLAN)",
    listDetails: [
      "Prior Analysis",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "70 Selected Keywords Targeting",
      "50 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of anchors",
      "Inclusion of anchors Indexing Modifications",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ’s",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
      "Blog Content Creation",
      "Local SEO",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "smm-services",
    packageName: "SMM STARTUP",
    pricing: "399.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "2 Social Media Accounts (Facebook + Instagram)",
      "3-5 Posts per week",
      "Content Creation",
      "Business Page Optimization",
      "Social Media Strategy (Overview)",
      "Facebook Likes Campaign",
      "Monthly Progress report",
      "Copy Writing",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "smm-services",
    packageName: "SMM BOOSTER",
    pricing: "699.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "4 Social Media Accounts (Facebook + Twitter + Instagram + Google+ etc.)",
      "Copywriting & Visual designs",
      "Business Page Optimization",
      "Ad Campaign Management",
      "Spam monitoring",
      "Monthly Progress report",
      "7 Posts per week Facebook + Twitter + Instagram + Google+",
      "Reputation Management",
      "Social Account Setup",
      "Content Creation",
      "Social Media Hearing",
      "Query and comments reply",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "smm-services",
    packageName: "SMM ULTIMATE",
    pricing: "999.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "4 Social Media Accounts (Facebook + Twitter + Instagram + Google+ etc.)",
      "Short Clip Commercial Videos",
      "Video Editing",
      "Copywriting & Visual Designs",
      "Customised Covers",
      "Campaigns / Contests",
      "Business Page Optimization",
      "Ad Campaign Management",
      "Spam monitoring",
      "Social Account Setup",
      "Content Creation",
      "Social Media Hearing",
      "Query and comments reply",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "creative-copywriting",
    packageName: "Web Content Basic Package",
    pricing: "129.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "1 Page Professional Copywriting Service",
      "Creative & Well-Written by 1 Professional Copywriter",
      "Industry Specified Expert Copywriter",
      "300 Words Per Page",
      "5 Revisions",
      "3 to 4 Business Days Rotation",
      "According To Your Exact Requirements",
      "Proofing by our in-house experts",
      "100% Original Content",
      "100% Approval Assurance",
      "30 Days Refund Warranty",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "creative-copywriting",
    packageName: "Web Content Start Up Package",
    pricing: "499.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "5 Pages Professional Copywriting Service",
      "Creative & Well-Written by 2 Professional Copywriters",
      "Industry Specified Expert Copywriters",
      "300 Words Per Page",
      "10 Revisions",
      "5 to 7 Business Days Rotation",
      "According To Your Exact Requirements",
      "Proofing by our in-house experts",
      "FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.",
      "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
      "100% Original Content",
      "100% Approval Assurance",
      "30 Days Refund Warranty",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "creative-copywriting",
    packageName: "Web Content Professional Package",
    pricing: "849.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "10 Pages Professional Copywriting Service",
      "Creative & Well-Written by 2 Professional Copywriters",
      "Industry Specified Expert Copywriters",
      "300 Words Per Page",
      "Unlimited Revisions",
      "7 to 10 Business Days Rotation",
      "According To Your Exact Requirements",
      "Proofing by our in-house experts",
      "FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.",
      "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
      "100% Ownership Rights",
      "100% Original Content",
      "100% Approval Assurance",
      "30 Days Refund Warranty",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "creative-copywriting",
    packageName: "Web Content Elite Package",
    pricing: "1849.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "Up to 20 Pages Professional Copywriting Service",
      "Creative & Well-Written by 3 Professional Copywriters",
      "Industry Specified Expert Copywriters",
      "300 Words Per Page",
      "Unlimited Revisions",
      "7 to 10 Business Days Rotation",
      "According To Your Exact Requirements",
      "Proofing by our in-house experts",
      "FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.",
      "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
      "100% Original Content",
      "100% Approval Assurance",
      "30 Days Refund Warranty",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "creative-copywriting",
    packageName: "Web Content Identity Package",
    pricing: "149.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "1 Creative, Fresh & Well-Written Article",
      "By 1 Professional Copywriter",
      "Industry Specified Expert Copywriter",
      "400 Words Per Page",
      "3 to 5 Business Days Rotation",
      "5 Revisions",
      "According To Your Exact Requirements",
      "Written on Your Specified Topic/Keyword",
      "Proofing by our in-house experts",
      "Free Submission on any article marketing directories /blog (If required)",
      "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
      "100% Original Content",
      "100% Approval Assurance",
      "30 Days Refund Warranty",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    title: "creative-copywriting",
    packageName: "Web Content Corporate Package",
    pricing: "129.00",
    quality: "Suitable for potential super-startups and brand revamps for companies.",
    listDetails: [
      "1 Creative, Fresh & Well-Written Article",
      "By 1 Professional Copywriter",
      "Industry Specified Expert Copywriter",
      "400 Words Per Page",
      "3 to 5 Business Days Rotation",
      "5 Revisions",
      "According To Your Exact Requirements",
      "Written on Your Specified Topic/Keyword",
      "Proofing by our in-house experts",
      "Free Submission on any article marketing directories /blog (If required)",
      "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
      "100% Original Content",
      "100% Approval Assurance",
      "30 Days Refund Warranty",
      "100% Satisfaction",
      "100% Ownership Rights*",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
];

export default PricingContent;
