interface PricingDetails {
  title: string;
  packageName: string;
  pricing: string;
  quality: string;
  listDetails: string[];
}

const PricingContent: PricingDetails[] = [
  {
    title: "logo-design",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "logo-design",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "logo-design",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "logo-design",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "logo-design",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "logo-design",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "website-design",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "website-design",
    packageName: "Website Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "website-design",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "website-design",
    packageName: "Website Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "website-design",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "digital-marketing",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "digital-marketing",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "digital-marketing",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "digital-marketing",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "digital-marketing",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "mobile-apps",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "mobile-apps",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "mobile-apps",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "mobile-apps",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "mobile-apps",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "mobile-apps",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "video-animation",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "video-animation",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "video-animation",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "video-animation",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "video-animation",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "instant basic Package",
    pricing: "39.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "Logo Startup Package",
    pricing: "50.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
  {
    title: "marketing-collateral",
    packageName: "instant Gold Package",
    pricing: "60.00",
    quality: "There are many variations of passages of Lorem",
    listDetails: [
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
      "There are many variations of passages",
    ],
  },
];

export default PricingContent;
